#!/bin/sh

# /etc/rc
# part of m0n0wall (http://neon1.net/m0n0wall)
#
# Copyright (C) 2003 Manuel Kasper <mk@neon1.net>.
# All rights reserved.

stty status '^T'

trap : 2
trap : 3

HOME=/
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export HOME PATH

set -T
trap "echo 'Reboot interrupted'; exit 1" 3

# make some directories in /var
mkdir /var/run /var/log /var/etc /var/db

# generate circular logfiles
clog -i -s 262144 /var/log/system.log
clog -i -s 262144 /var/log/filter.log
clog -i -s 32768 /var/log/dhcpd.log
chmod 0600 /var/log/system.log /var/log/filter.log /var/log/dhcpd.log

adjkerntz -i

# Create an initial utmp file
cd /var/run && cp /dev/null utmp && chmod 644 utmp

# Build devices database
dev_mkdb

# Run ldconfig
/sbin/ldconfig -elf /usr/lib

# let the PHP-based configuration subsystem set up the system now
/etc/rc.bootup

/etc/rc.banner

exit 0
